### PR TITLE
Complete project with merge of feature/project branch

### PR DESCRIPTION
**Pull request by defoebrand**
This project is a 'micro-reddit' that allows users to be created, users to create posts, and users to comment on posts. Non-users are not allowed to create posts or comments.

### CODE REVIEW

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required 🔧 

Great job so far! You almost pass all the tests! The password for the user is not being validated for presence, you must ensure that the password for the user is not blank, please fix that.

## What to do now?

Implement the changes and ask for another CRR.

You can find me in slack as **srodrig**, happy coding! :wave:

**Comment by m15e** [comment]
Hi at @santiago-rodrig thanks for the quick review. The image below shows our code and our output, which includes password presence validation on line 5 and the console output at the bottom which shows that a user can't be created without a password. Please clarify how we can validate the password for presence beyond that. Thank you

password_presence

**Comment by Dandush03** [comment]
# Status: :rocket: Project Approved :rocket: 

## Great work on this project, good luck on the next one

# Happy Coding :nerd_face: :computer:

**Pull request merged**
